id: P008093
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1677
  title: དཔལ་ས་སྐྱའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    ec9a0a7824a74faa84d08053201c59f0:
      image_group_id: I1KG1838
      title: Volume 1 of dpal sa skya'i zhal 'don phyogs bsgrigs
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
ebook_metadata:
  title: དཔལ་ས་སྐྱའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P008093
  cover: cover.jpg
  layers:
  - pagination
