id: P008093
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1677
  title: དཔལ་ས་སྐྱའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    2d5d54f5bb784655aa9f4f6f8431874b:
      image_group_id: I1KG1838
      title: ''
      volume_number: 1
      total_pages: 362
ebook_metadata:
  title: དཔལ་ས་སྐྱའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P008093
  cover: cover.jpg
  layers:
  - pagination
