id: I29B9671D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T19:14:30+00:00'
last_modified: '2022-06-09T04:26:49.071155+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1677
  title: དཔལ་ས་སྐྱའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A5C9:
      image_group_id: I1KG1838
      title: Volume 1 of dpal sa skya'i zhal 'don phyogs bsgrigs
      total_pages: 362
      order: 1
      base_file: A5C9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
